# Generated by Django 5.2.11 on 2026-05-10 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputados', '0005_proposicaoautor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('tipo_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('fase_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('transcricao', models.TextField(blank=True, null=True)),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discursos', to='deputados.deputado')),
            ],
        ),
        migrations.CreateModel(
            name='PresencaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.IntegerField()),
                ('data_presenca', models.DateField(blank=True, null=True)),
                ('tipo_participacao', models.CharField(blank=True, max_length=100, null=True)),
                ('status_presenca', models.CharField(blank=True, max_length=100, null=True)),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_eventos', to='deputados.deputado')),
            ],
            options={
                'verbose_name_plural': 'Presenças em Eventos',
                'unique_together': {('id_evento', 'deputado')},
            },
        ),
    ]
