# Generated by Django 5.2.11 on 2026-05-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputados', '0006_discurso_presencaevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='situacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
