# Generated by Django 5.2.11 on 2026-05-21 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputados', '0007_proposicao_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('tipo_despesa', models.CharField(max_length=200)),
                ('cod_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_lote', models.IntegerField(blank=True, null=True)),
                ('cod_tipo_documento', models.IntegerField(blank=True, null=True)),
                ('data_documento', models.DateField(blank=True, null=True)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=500, null=True)),
                ('cnpj_cpf_fornecedor', models.CharField(blank=True, max_length=20, null=True)),
                ('num_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('num_ressarcimento', models.CharField(blank=True, max_length=100, null=True)),
                ('parcela', models.IntegerField(blank=True, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('url_documento', models.URLField(blank=True, max_length=1000, null=True)),
                ('valor_documento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_glosa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='deputados.deputado')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'indexes': [models.Index(fields=['deputado', 'ano', 'mes'], name='deputados_d_deputad_33521f_idx')],
            },
        ),
    ]
