# Generated by Django 5.2.11 on 2026-05-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputados', '0008_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='num_autores_deputados',
            field=models.IntegerField(blank=True, help_text='Qtd de deputados coautores desta proposição (cache denormalizado)', null=True),
        ),
        migrations.AddField(
            model_name='votacao',
            name='polarizacao',
            field=models.FloatField(blank=True, help_text='Fração do voto dominante (0.5 a 1.0). Ex: 0.95 = 95% votaram igual', null=True),
        ),
    ]
