# Generated by Django 5.2.11 on 2026-05-10 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0003_remove_deputadoanalise_community_fields'),
        ('deputados', '0006_discurso_presencaevento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deputadoanalise',
            options={'ordering': ['-presenca_percentual'], 'verbose_name': 'Analise de Deputado', 'verbose_name_plural': 'Analises de Deputados'},
        ),
        migrations.AlterField(
            model_name='deputadoanalise',
            name='deputado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='deputados.deputado'),
        ),
        migrations.AlterField(
            model_name='deputadoanalise',
            name='presenca_percentual',
            field=models.FloatField(help_text='Percentual de presenca nas votacoes (0 a 100)'),
        ),
        migrations.AlterField(
            model_name='deputadoanalise',
            name='votacoes_presente',
            field=models.IntegerField(help_text='Qtd de votacoes em que o deputado votou'),
        ),
        migrations.AlterField(
            model_name='deputadoanalise',
            name='votacoes_total',
            field=models.IntegerField(help_text='Total de votacoes na legislatura'),
        ),
        migrations.CreateModel(
            name='AtividadeDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pontuacao', models.FloatField(default=0.0)),
                ('intensidade', models.IntegerField(default=0, help_text='Quartil de intensidade (0 a 4)')),
                ('detalhes', models.JSONField(default=dict, help_text='Dicionario com contagem e descricao das acoes no dia')),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_diarias', to='deputados.deputado')),
            ],
            options={
                'verbose_name': 'Atividade Diaria',
                'verbose_name_plural': 'Atividades Diarias',
                'db_table': 'atividade_diaria',
                'ordering': ['-data'],
                'unique_together': {('deputado', 'data')},
            },
        ),
    ]
