# Generated by Django 5.2.11 on 2026-05-10 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputados', '0005_proposicaoautor'),
        ('grafos', '0003_grafoaresta_coautoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackboneAresta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislatura', models.IntegerField()),
                ('metodo', models.CharField(choices=[('high_salience_skeleton', 'High Salience Skeleton'), ('lans', 'LANS')], max_length=30)),
                ('tipo_grafo', models.CharField(choices=[('similaridade', 'Similaridade de votos'), ('coautoria', 'Coautoria')], max_length=20)),
                ('peso', models.FloatField(help_text='Peso original da aresta (similaridade ou coautoria)')),
                ('deputado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backbone_arestas_como_1', to='deputados.deputado')),
                ('deputado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backbone_arestas_como_2', to='deputados.deputado')),
            ],
            options={
                'verbose_name': 'Aresta de Backbone',
                'verbose_name_plural': 'Arestas de Backbone',
                'ordering': ['-peso'],
                'indexes': [models.Index(fields=['legislatura', 'metodo', 'tipo_grafo'], name='grafos_back_legisla_b97147_idx')],
                'unique_together': {('deputado_1', 'deputado_2', 'legislatura', 'metodo', 'tipo_grafo')},
            },
        ),
    ]
