# Generated by Django 5.2.11 on 2026-05-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('erro_mensagem', models.TextField(blank=True, null=True)),
                ('deputados_atualizados', models.IntegerField(default=0)),
                ('partidos_atualizados', models.IntegerField(default=0)),
                ('orgaos_atualizados', models.IntegerField(default=0)),
                ('votacoes_adicionadas', models.IntegerField(default=0)),
                ('votos_adicionados', models.IntegerField(default=0)),
                ('proposicoes_adicionadas', models.IntegerField(default=0)),
                ('autores_adicionados', models.IntegerField(default=0)),
                ('discursos_adicionados', models.IntegerField(default=0)),
                ('presencas_adicionadas', models.IntegerField(default=0)),
                ('despesas_adicionadas', models.IntegerField(default=0)),
                ('tempo_execucao_segundos', models.FloatField(default=0.0)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Execução de Update de Dados',
                'verbose_name_plural': 'Execuções de Update de Dados',
                'db_table': 'execucao_update',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
